Added logoff disconnected option and admin address to allow running t…
umn-microsoft-automation/UMN-Citrix pull request #2
Opened 2020-12-18 07:12 UTC by dpalchuk

Added logoff disconnected option and admin address to allow running the script from remote workstations.

2020-12-29 18:06 UTC, FISHMANPET reviewed
I wanted to comment on the 3 new files separately from the update to the existing file.

Relating to my comments about specifying the path to the config as a parameter, and renaming the XML file, the idea would be that someone using these scripts can just pull the latest version from GitHub when you make updates, and they won't have to fight with merge conflicts or anything like that.  So I think it would make more sense to specify the path as a parameter (maybe with a default value of the file in the current directory?) rather than asking people to edit the file.  I see the benefit in updating the file, so you can just easily call the script without having to worry about passing in the path to the config every time, so I'm not sure that my way is strictly better than what you've done.  So I'll leave it up to you about how to handle that ultimately, just thought I'd point out another way I've seen it done.

Another thing is that the cases where you detect an error, write it to the console in red, and then exit.  Exiting like that indicates to the terminal that the script exited successfully, which might be important if someone were to use this script in another script.

Two ways to improve that I think, neither better than the other, just situationally dependent.
First, you can replace the `Write-Host -ForegroundColor Red` with [`Write-Error`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-error?view=powershell-5.1) which will write a non-terminating error to the console, in red text, and also add an entry to the shell's `$error` variable.  Then run [`exit 1`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-5.1#exit) (or some value that isn't 0) to indicate the script exited with a failure.  `Write-Error` produces non-terminating errors, but then the `$ErrorActionPreference` variable is set to `"Stop"` (either in your script, or in the users' terminal environment), Write-Error will be a "terminating" error that will stop execution of the script, and your `exit 1` wouldn't be called.
Another way is to replace the Write-Host and the Exit with a [`throw`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_throw?view=powershell-5.1).  This will write the message to the console in Red, populate the `$error` variable, and end execution of the script.
The first way would be useful if someone is treating the script as just another executable, the second is useful if someone wants to treat the script as PowerShell and handle failures in a PowerShell way.
[This StackOverflow answer](https://stackoverflow.com/a/28724558) explains it a little better, In your case, I'd probably lean towards still using exit because I doubt there's much an automation could do to handle the failures you're detecting.

2020-12-29 18:18 UTC, FISHMANPET requested changes
The only changes I think are needed here are how you handle the LogoffDisconnected value, you should treat it like a boolean instead of casting it into a string so it can be turned back into a boolean.

2020-12-29 18:18 UTC, FISHMANPET commented on Start-DesktopGroupReboot.ps1
> +if ([string]::IsNullOrEmpty($adminaddress)) {
I think you could just make this a mandatory parameter which will do this checking for you, but there's not an easy way to include a text prompt like you're doing here.

2020-12-29 18:18 UTC, FISHMANPET commented on Start-DesktopGroupReboot.ps1
> +    [bool]$LogoffDisconnected,
This could be a [switch](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-5.1#switch-parameters) parameter.

Though regardless if it's a `[bool]` or a `[switch]`, you should treat it like a boolean rather than force casting it to a string and then checking against `"True"`.

These two statements are equivalent:
```powershell
if ($LogoffDisconnected -eq "True") {}
```
```powershell
if ($LogoffDisconnected) {}
```

2020-12-30 06:01 UTC, dpalchuk commented on PVS-Automation/Create-PVSDiskUpdateVersion.ps1
> +[xml]$ConfigFile = Get-Content "C:\automation\InteractivePVSConfig.xml"
Added parameter as well as default value of same directory as the script.

2020-12-30 06:01 UTC, dpalchuk commented on PVS-Automation/Create-PVSDiskUpdateVersion.ps1
> +if ([string]::IsNullOrEmpty($updatemachine) -and (![string]::IsNullOrEmpty($UpdateCollection)) ) {
Corrected the duplicate if statement

2020-12-30 06:02 UTC, dpalchuk commented on PVS-Automation/Create-PVSDiskUpdateVersion.ps1
> +elseif ([string]::IsNullOrEmpty($updatemachine) -and (![string]::IsNullOrEmpty($UpdateCollection)) ) {
Fixed the ! in $updatecollection.

2020-12-30 06:09 UTC, dpalchuk commented on PVS-Automation/InteractivePVSConfig.xml
> +<?xml version="1.0"?>
Renamed the config file and added notes in scripts and XML

2020-12-30 06:26 UTC, dpalchuk commented on Start-DesktopGroupReboot.ps1
> +    [bool]$LogoffDisconnected,
Replaced with if ($LogoffDisconnected) {}

2020-12-30 06:30 UTC, dpalchuk commented on Start-DesktopGroupReboot.ps1
> +if ([string]::IsNullOrEmpty($adminaddress)) {
Mandatory parameter did not work with pre-populated parameter value. It still prompts. Since controllers don't change often I opted to allow pre-configuration of that field for ease of use.

2021-01-04 20:29 UTC, FISHMANPET requested changes
I think just update the Get-Content to fail when it can't find the file and this will be good

2021-01-04 20:29 UTC, FISHMANPET commented on PVS-Automation/Promote-PVSDiskUpdateVersion.ps1
> +    [xml]$ConfigFile = Get-Content "$myDir\InteractivePVSConfig.xml"
If the config file doesn't exist, Get-Content will throw a useful error message, but it won't treat it as a terminating error, so it will keep going, which will I assume cause other problems farther down the line.  I think the easiest way to fix that is to add `-ErrorAction Stop` to the Get-Content so if it encounters an error it will terminate.

2021-01-04 22:40 UTC, dpalchuk commented on PVS-Automation/Promote-PVSDiskUpdateVersion.ps1
> +    [xml]$ConfigFile = Get-Content "$myDir\InteractivePVSConfig.xml"
done

2021-01-04 22:45 UTC, FISHMANPET approved these changes

2021-01-04 22:46 UTC, merged